### PR TITLE
Use .glyphspackage

### PR DESCRIPTION
**Pull request by moyogo**
The replaces the .glyphs file by a .glyphspackage.

### CODE REVIEW

**Comment by n8willis** [comment]
Asking purely out of my own curiosity, apart from `diff`ing, are there long-term advantages to using glyphspackage as the source format?

**Comment by moyogo** [comment]
@n8willis Besides the format being created for CJK initially, all the other advantages are for diffing. It’s easier to spot what has changed, no random reordering, more manageable merging issues. I don’ know why all GF projects are not gradually converted from .glyphs to .glyphpackages.

**Comment by n8willis** [comment]
@moyogo ACK. Probably the googlefonts-project-template will need to migrate to it for real momentum. I noticed that it's been talked up already: [googlefonts-project-template#64](https://github.com/googlefonts/googlefonts-project-template/issues/64) but paused ... maybe time to revisit that.

**Comment by YADAMSS** [comment]
Thanks @moyogo @n8willis !

**Pull request merged**
